### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by gmcdowell** [jthegedus/asdf-firebase#22]
Just wondering if ongoing support has been abandoned or not?

**Comment by mrfelipelima** [comment]
Yes i'm wanna know too.

**Comment by jthegedus** [comment]
It has not been abandoned. I just haven't used it in a while and so didn't realise it wasn't working until just this moment.

For whatever reason, GitHub has not been sending me notifications for new issues on my repos, so I have been missing a lot of stuff.

**Comment by jthegedus** [comment]
The issue I have run into is the sort algorithm for the versions list is incorrect and so determining which version is `latest` is wrong. It technically still works to install all versions of the Firebase CLI
